package com.internal.copycat

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.project.guessProjectDir
import com.intellij.openapi.util.IconLoader
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.ui.JBColor
import com.intellij.util.ui.JBUI
import java.awt.*
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import javax.swing.*
import javax.swing.border.EmptyBorder

// Auto-generated detection

private val AUTO_GENERATED_FOLDER_NAMES = setOf(
    "node_modules", "build", "dist", "out", ".gradle", ".idea",
    "generated", "gen", "generated-sources", ".next", ".nuxt",
    "vendor", "__pycache__", ".pytest_cache", "target", "bin", "obj",
    ".dart_tool", "pods", ".build", "deriveddata", "coverage",
    ".nyc_output", "storybook-static", ".angular", "bazel-bin",
    "bazel-out", ".output", "protoc-gen", ".turbo", ".vercel",
    ".svelte-kit", "prisma/generated", "__generated__"
)

private val AUTO_GENERATED_FILE_MARKERS = listOf(
    "@generated", "auto-generated", "do not edit",
    "code generated", "generated by", "automatically generated",
    "this file was generated", "this file is auto-generated"
)

private fun isAutoGeneratedFolder(folder: VirtualFile) =
    folder.name.lowercase() in AUTO_GENERATED_FOLDER_NAMES

private fun isAutoGeneratedFile(file: VirtualFile): Boolean {
    return try {
        val firstLines = String(file.contentsToByteArray())
            .lines().take(5).joinToString("\n").lowercase()
        AUTO_GENERATED_FILE_MARKERS.any { firstLines.contains(it) }
    } catch (e: Exception) { false }
}

// Panel

class CopyCatLocPanel(private val project: Project) : JPanel(BorderLayout()) {

    private val statsPanel   = JPanel().apply { layout = BoxLayout(this, BoxLayout.Y_AXIS); background = bg() }
    private val foldersPanel = JPanel().apply { layout = BoxLayout(this, BoxLayout.Y_AXIS); background = bg() }
    private val scanButton   = JButton("Scan Project")

    init {
        background = bg()

        val topBar = JPanel(FlowLayout(FlowLayout.LEFT)).apply { background = bg() }
        scanButton.addActionListener { runScan() }
        topBar.add(scanButton)

        val scroll = JScrollPane(foldersPanel).apply {
            border = null
            background = bg()
            viewport.background = bg()
        }

        val center = JPanel(BorderLayout()).apply {
            background = bg()
            border = JBUI.Borders.empty(8, 12)
            add(statsPanel, BorderLayout.NORTH)
            add(scroll, BorderLayout.CENTER)
        }

        add(topBar, BorderLayout.NORTH)
        add(center, BorderLayout.CENTER)
    }

    private fun runScan() {
        scanButton.isEnabled = false
        scanButton.text = "Scanning..."
        statsPanel.removeAll(); statsPanel.revalidate(); statsPanel.repaint()
        foldersPanel.removeAll(); foldersPanel.revalidate(); foldersPanel.repaint()

        ApplicationManager.getApplication().executeOnPooledThread {
            val root = project.guessProjectDir() ?: return@executeOnPooledThread

            val regularFolders    = mutableListOf<FolderStats>()
            val autoGenFolders    = mutableListOf<VirtualFile>()
            val rootFileStats     = mutableListOf<FileStats>()

            for (child in root.children) {
                if (child.name.startsWith(".")) continue
                when {
                    child.isDirectory && isAutoGeneratedFolder(child) -> autoGenFolders.add(child)
                    child.isDirectory                                  -> regularFolders.add(scanFolder(child))
                    else                                               -> scanFile(child)?.let { rootFileStats.add(it) }
                }
            }

            val allFiles      = regularFolders.flatMap { it.allFiles } + rootFileStats
            val totalLines    = allFiles.sumOf { it.totalLines }
            val noComments    = allFiles.sumOf { it.linesWithoutComments }
            val totalBytes    = allFiles.sumOf { it.sizeBytes }
            val codeFiles     = allFiles.filter { it.linesWithoutComments > 0 }
            val codeOnlyLines = codeFiles.sumOf { it.linesWithoutComments }

            SwingUtilities.invokeLater {
                statsPanel.removeAll()
                statsPanel.add(statRow("Total lines of code",    "$totalLines lines",    formatSize(totalBytes), null))
                statsPanel.add(statRow("Without comments",       "$noComments lines",    formatSize(totalBytes), "− ${totalLines - noComments} lines"))
                statsPanel.add(statRow("Code-only files total",  "$codeOnlyLines lines", "${codeFiles.size} files", "− ${totalLines - codeOnlyLines} lines"))
                statsPanel.add(Box.createVerticalStrut(8))
                statsPanel.add(JSeparator().apply { maximumSize = Dimension(Int.MAX_VALUE, 1) })
                statsPanel.add(Box.createVerticalStrut(8))

                foldersPanel.removeAll()
                foldersPanel.border = JBUI.Borders.emptyBottom(12)

                // Regular folders
                for (fs in regularFolders.sortedByDescending { it.totalLines }) {
                    foldersPanel.add(FolderChip(fs))
                    foldersPanel.add(Box.createVerticalStrut(4))
                }

                // Auto-generated folders
                if (autoGenFolders.isNotEmpty()) {
                    foldersPanel.add(Box.createVerticalStrut(12))
                    foldersPanel.add(sectionLabel("Auto Generated — not included in stats above"))
                    foldersPanel.add(Box.createVerticalStrut(6))
                    for (folder in autoGenFolders) {
                        foldersPanel.add(AutoGeneratedChip(folder, project))
                        foldersPanel.add(Box.createVerticalStrut(4))
                    }
                }

                scanButton.isEnabled = true
                scanButton.text = "Scan Project"
                statsPanel.revalidate(); statsPanel.repaint()
                foldersPanel.revalidate(); foldersPanel.repaint()
            }
        }
    }

    private fun sectionLabel(text: String) = JLabel(text).apply {
        font = font.deriveFont(Font.BOLD, 11f)
        foreground = UIManager.getColor("Label.disabledForeground")
        alignmentX = LEFT_ALIGNMENT
        border = JBUI.Borders.emptyBottom(2)
    }

    private fun statRow(label: String, value: String, sub: String, diff: String?): JPanel {
        val row = JPanel(FlowLayout(FlowLayout.LEFT, 6, 2)).apply {
            background = bg()
            maximumSize = Dimension(Int.MAX_VALUE, 26)
            alignmentX = LEFT_ALIGNMENT
        }
        row.add(JLabel("$label:").apply { font = font.deriveFont(Font.BOLD) })
        row.add(JLabel(value))
        row.add(JLabel("($sub)").apply { foreground = UIManager.getColor("Label.disabledForeground") })
        if (diff != null) row.add(JLabel(diff).apply { foreground = Color(0x4CAF50) })
        return row
    }

    private fun scanFolder(folder: VirtualFile): FolderStats {
        val files = mutableListOf<FileStats>()
        collectFiles(folder, files)
        return FolderStats(
            folder, files,
            files.sumOf { it.totalLines },
            files.sumOf { it.linesWithoutComments },
            files.sumOf { it.sizeBytes }
        )
    }

    private fun collectFiles(dir: VirtualFile, result: MutableList<FileStats>) {
        for (child in dir.children) {
            when {
                child.isDirectory && isAutoGeneratedFolder(child) -> { /* skip auto-generated subfolders */ }
                child.isDirectory -> collectFiles(child, result)
                else -> scanFile(child)?.let { result.add(it) }
            }
        }
    }

    private fun scanFile(file: VirtualFile): FileStats? {
        return try {
            val content    = String(file.contentsToByteArray())
            val total      = content.lines().size
            var stripped   = content
            stripped = stripped.replace(Regex("/\\*[\\s\\S]*?\\*/"), "")
            stripped = stripped.replace(Regex("//[^\n]*"), "")
            stripped = stripped.replace(Regex("(?m)^\\s*#[^\n]*"), "")
            stripped = stripped.replace(Regex("<!--[\\s\\S]*?-->"), "")
            val noComments = stripped.lines().count { it.isNotBlank() }
            FileStats(file, total, noComments, file.length)
        } catch (e: Exception) { null }
    }
}

// Auto Generated Chip

class AutoGeneratedChip(
    private val folder: VirtualFile,
    private val project: Project
) : JPanel(BorderLayout()) {

    private val body = JPanel(BorderLayout()).apply { background = bg() }

    init {
        background = bg()
        border = BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color(0xF0A500), 1, true),
            JBUI.Borders.empty(6, 10)
        )
        alignmentX = LEFT_ALIGNMENT
        maximumSize = Dimension(Int.MAX_VALUE, Int.MAX_VALUE)

        showDefaultState()
        add(body, BorderLayout.CENTER)
    }

    private fun showDefaultState() {
        body.removeAll()

        val row = JPanel(FlowLayout(FlowLayout.LEFT, 6, 0)).apply { background = bg() }

        val nameLabel = JLabel(folder.name).apply {
            font = font.deriveFont(Font.BOLD)
            foreground = Color(0xF0A500)
        }

        val badge = JLabel("Auto Generated").apply {
            font = font.deriveFont(Font.PLAIN, 10f)
            foreground = JBColor.WHITE
            background = Color(0xF0A500)
            isOpaque = true
            border = JBUI.Borders.empty(2, 6)
        }

        val hint = JLabel("Click to analyze").apply {
            font = font.deriveFont(Font.ITALIC, 10f)
            foreground = UIManager.getColor("Label.disabledForeground")
            border = JBUI.Borders.emptyLeft(6)
        }

        row.add(nameLabel)
        row.add(badge)
        row.add(hint)
        body.add(row, BorderLayout.CENTER)
        body.cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)

        body.addMouseListener(object : MouseAdapter() {
            override fun mouseClicked(e: MouseEvent) {
                val confirmed = JOptionPane.showConfirmDialog(
                    this@AutoGeneratedChip,
                    "<html><b>${folder.name}</b> appears to be auto-generated.<br>" +
                            "Analyzing it may take a few seconds depending on its size.<br><br>" +
                            "Do you want to proceed?</html>",
                    "Analyze Auto-Generated Folder",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
                )
                if (confirmed == JOptionPane.YES_OPTION) analyzeFolder()
            }
        })

        body.revalidate(); body.repaint()
    }

    private fun analyzeFolder() {
        body.removeAll()
        body.cursor = Cursor.getDefaultCursor()

        val loadingRow = JPanel(FlowLayout(FlowLayout.LEFT, 6, 0)).apply { background = bg() }
        loadingRow.add(JLabel(folder.name).apply { font = font.deriveFont(Font.BOLD); foreground = Color(0xF0A500) })
        loadingRow.add(JLabel("Analyzing...").apply { foreground = UIManager.getColor("Label.disabledForeground") })
        body.add(loadingRow, BorderLayout.CENTER)
        body.revalidate(); body.repaint()

        ApplicationManager.getApplication().executeOnPooledThread {
            val files = mutableListOf<FileStats>()
            deepCollect(folder, files)

            val totalLines = files.sumOf { it.totalLines }
            val noComments = files.sumOf { it.linesWithoutComments }
            val bytes      = files.sumOf { it.sizeBytes }

            SwingUtilities.invokeLater {
                body.removeAll()

                val header = JPanel(BorderLayout()).apply { background = bg() }
                val info   = JPanel(FlowLayout(FlowLayout.LEFT, 6, 0)).apply { background = bg() }
                info.add(JLabel(folder.name).apply { font = font.deriveFont(Font.BOLD) })
                info.add(separator())
                info.add(JLabel("$totalLines lines"))
                info.add(JLabel("($noComments without comments)").apply { foreground = UIManager.getColor("Label.disabledForeground") })
                info.add(JLabel(formatSize(bytes)).apply { foreground = Color(0x2D7DD2) })
                header.add(info, BorderLayout.CENTER)

                val filesContainer = JPanel().apply {
                    layout = BoxLayout(this, BoxLayout.Y_AXIS)
                    background = bg()
                    border = JBUI.Borders.empty(6, 20, 4, 0)
                }
                for (fs in files.sortedByDescending { it.totalLines }) {
                    filesContainer.add(FileChip(fs))
                    filesContainer.add(Box.createVerticalStrut(3))
                }

                body.add(header, BorderLayout.NORTH)
                body.add(filesContainer, BorderLayout.CENTER)

                // Update border to normal after analysis
                this@AutoGeneratedChip.border = BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(
                        UIManager.getColor("Separator.foreground") ?: JBColor.GRAY, 1, true
                    ),
                    JBUI.Borders.empty(6, 10)
                )

                body.revalidate(); body.repaint()
                parent?.revalidate(); parent?.repaint()
            }
        }
    }

    private fun deepCollect(dir: VirtualFile, result: MutableList<FileStats>) {
        for (child in dir.children) {
            if (child.isDirectory) deepCollect(child, result)
            else {
                try {
                    val content    = String(child.contentsToByteArray())
                    val total      = content.lines().size
                    var stripped   = content
                    stripped = stripped.replace(Regex("/\\*[\\s\\S]*?\\*/"), "")
                    stripped = stripped.replace(Regex("//[^\n]*"), "")
                    stripped = stripped.replace(Regex("(?m)^\\s*#[^\n]*"), "")
                    stripped = stripped.replace(Regex("<!--[\\s\\S]*?-->"), "")
                    val noComments = stripped.lines().count { it.isNotBlank() }
                    result.add(FileStats(child, total, noComments, child.length))
                } catch (_: Exception) {}
            }
        }
    }
}

// Regular Chips

class FolderChip(private val stats: FolderStats) : JPanel(BorderLayout()) {
    private var expanded = false
    private val filesContainer = JPanel().apply {
        layout = BoxLayout(this, BoxLayout.Y_AXIS)
        background = bg()
        border = JBUI.Borders.empty(6, 20, 4, 0)
        isVisible = false
    }
    private val upIcon   = tryIcon("/icons/up.svg")
    private val downIcon = tryIcon("/icons/down.svg")
    private val toggleBtn = JLabel(downIcon ?: run { null }).apply {
        if (downIcon == null) (this as JLabel).text = "▶"
        cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)
        border = JBUI.Borders.emptyLeft(8)
    }

    init {
        background = bg()
        border = BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(
                UIManager.getColor("Separator.foreground") ?: JBColor.GRAY, 1, true
            ),
            JBUI.Borders.empty(6, 10)
        )
        alignmentX = LEFT_ALIGNMENT
        maximumSize = Dimension(Int.MAX_VALUE, Int.MAX_VALUE)

        val header = JPanel(BorderLayout()).apply { background = bg() }
        val info   = JPanel(FlowLayout(FlowLayout.LEFT, 6, 0)).apply { background = bg() }

        info.add(JLabel(stats.folder.name).apply { font = font.deriveFont(Font.BOLD) })
        info.add(separator())
        info.add(JLabel("${stats.totalLines} lines"))
        info.add(JLabel("(${formatSize(stats.sizeBytes)})").apply {
            foreground = UIManager.getColor("Label.disabledForeground")
        })

        header.add(info, BorderLayout.CENTER)
        header.add(toggleBtn, BorderLayout.EAST)

        for (fs in stats.allFiles.sortedByDescending { it.totalLines }) {
            filesContainer.add(FileChip(fs))
            filesContainer.add(Box.createVerticalStrut(3))
        }

        val toggle = object : MouseAdapter() {
            override fun mouseClicked(e: MouseEvent) = toggle()
        }
        header.addMouseListener(toggle)
        toggleBtn.addMouseListener(toggle)

        add(header, BorderLayout.NORTH)
        add(filesContainer, BorderLayout.CENTER)
    }

    private fun toggle() {
        expanded = !expanded
        filesContainer.isVisible = expanded
        if (upIcon != null && downIcon != null) {
            toggleBtn.icon = if (expanded) upIcon else downIcon
        } else {
            toggleBtn.text = if (expanded) "▼" else "▶"
        }
        revalidate(); repaint()
        parent?.revalidate(); parent?.repaint()
    }
}

class FileChip(private val stats: FileStats) : JPanel(FlowLayout(FlowLayout.LEFT, 6, 2)) {
    init {
        background = bg()
        alignmentX = LEFT_ALIGNMENT
        maximumSize = Dimension(Int.MAX_VALUE, 26)
        add(JLabel(stats.file.name).apply { font = font.deriveFont(Font.BOLD) })
        add(separator())
        add(JLabel("${stats.totalLines} lines"))
        add(JLabel("(${stats.linesWithoutComments} without comments)").apply {
            foreground = UIManager.getColor("Label.disabledForeground")
        })
        add(separator())
        add(JLabel(formatSize(stats.sizeBytes)).apply { foreground = Color(0x2D7DD2) })
    }
}

// Data classes

data class FileStats(val file: VirtualFile, val totalLines: Int, val linesWithoutComments: Int, val sizeBytes: Long)
data class FolderStats(val folder: VirtualFile, val allFiles: List<FileStats>, val totalLines: Int, val linesWithoutComments: Int, val sizeBytes: Long)

// Helpers

private fun bg()          = UIManager.getColor("Panel.background") ?: JBColor.WHITE
private fun separator()   = JSeparator(JSeparator.VERTICAL).apply { preferredSize = Dimension(1, 12) }
private fun formatSize(bytes: Long) = when {
    bytes < 1024        -> "$bytes B"
    bytes < 1024 * 1024 -> "${bytes / 1024} KB"
    else                -> String.format("%.1f MB", bytes / (1024.0 * 1024.0))
}
private fun tryIcon(path: String) = try {
    IconLoader.getIcon(path, FileChip::class.java)
} catch (e: Exception) { null }